[build]
  publish = "./build/static"
  functions = "./build/functions"

[[redirects]]
  from = "/terms-of-use"
  to = "/terms"
  status = 301

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/presta"
  status = 200
